### ISSUE TITLE
Where is install.sh?

### ISSUE THREAD

**Issue by elfeffe** [ppadial/autoMySQLBackup#1]
uh?

**Comment by ppadial** [comment]
u right!!!

thanks

**Comment by elfeffe** [comment]
When I try to run t, ti says

automysqlbackup ... exists and is readable ... md5sum failed :(

**Comment by ppadial** [comment]
update and try again, its fixed

**Comment by elfeffe** [comment]
it works, thank you!

**Comment by elfeffe** [comment]
Me acabo de dar cuenta de que los dos estamos en Málaga :)
Gracias

**Comment by ppadialitrs** [comment]
jajaja, cierto!! 

De nada ! :)
